palavra=input('Digite algo:')
print(f'O tipo primitivo desse valor é{type(palavra)}')
print(f'Só tem espaços?{n.isspace()}')
print(f'É um numero?{n.isalnum()}')
print(f'Está em maiscúlas?{n.isupper()}')
print(f'Está em minúsculas?{n.islower()}')
print(f'Está capitalizada?{n.istitle()}')